#! /bin/sh

# Functions
rule() { bspc rule -a "$@" & }
config() { bspc config "$@" & }
start() { pkill -x "$1"; { sleep 0.1; "$@" & }; }

# Bindings
pgrep -x sxhkd > /dev/null || sxhkd &

# Disable client-side decorations
gsettings set org.gnome.desktop.wm.preferences button-layout "" &

# Cursor
xsetroot -cursor_name left_ptr &

# Compositor
picom &

# Bar
$HOME/.config/polybar/launch.sh &

# Notifications
dunst &

# Polkit
[ -n "$(pidof polkit-gnome-authentication-agent-1)" ] || /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Power manager
[ -n "$(pidof xfce4-power-manager)" ] || xfce4-power-manager &

# Wallpaper
$HOME/.fehbg &

# Rules
rule kitty                          state=floating
rule mpv                            state=floating
rule Zathura                        state=floating
rule Thunar                         state=floating
rule feh                            state=floating
rule Lxappearance                   state=floating
rule firefox                        desktop=^2
rule discord                        desktop=^3
rule 'osu!.exe'                     desktop=^4 state=fullscreen
config external_rules_command "$HOME/.config/bspwm/scripts/spotifyrule.sh"

# Config
bspc monitor -d 1 2 3 4 5

config border_width                4
config window_gap                  10
config split_ratio                 0.5

config borderless_monocle          true
config gapless_monocle             true
config top_padding                 30
config bottom_padding              0
config left_padding                0
config right_padding               0
config focus_follows_pointer       true
config ignore_ewmh_focus           true

config pointer_modifier            Mod4
config pointer_action1             move
config pointer_action2             resize_side
config pointer_action2             resize_corner

config focused_border_color        "#c49ec4"
config normal_border_color         "#0A0D0F"
config active_border_color         "#0A0D0F"
